- name: download consul web-ui
  get_url: url={{ consul_ui_download }}
           dest={{ consul_download_folder }}

- name: copy and unpack ui
  unarchive: src={{ consul_download_folder }}/{{ consul_ui_archive }}
             dest={{ consul_home }}
             copy=no

- name: set ownership
  file: state=directory
        path={{consul_ui_dir}}
        owner={{consul_user}}
        group={{consul_group}}
        recurse=yes

