- hosts: localhost
  tasks:
  - ec2:
      key_name: "{{ key_name }}"
      instance_type: "{{ docker_instance }}"
      image: "{{ ami }}"
      wait: yes
      region: "{{ region }}"
      count: 1
      instance_tags:
          cpt: "dockerregistry"
          Name: "docker-registry"
      volumes:
        - device_name: /dev/sda1
          volume_size: 50
          delete_on_termination: true
      vpc_subnet_id: "{{ vpc_subnet_id }}"

