- hosts: localhost
  tasks:
  - ec2:
      key_name: "{{ key_name }}"
      instance_type: "{{ slave_instance }}"
      image: "{{ ami }}"
      wait: yes
      region: "{{ region }}"
      count: 1
      volumes:
        - device_name: /dev/sda1
          volume_size: 50
          delete_on_termination: true
      instance_tags:
         cpt: "slave"
         Name: "slave-{{ slave_id }}" 
      vpc_subnet_id: "{{ vpc_subnet_id }}"

