- hosts: tag_cpt_master
  user: "{{ user }}"
  sudo: yes
  gather_facts: true
  tasks:
   - name: setup hostname
     hostname: name="{{ ec2_tag_Name }}"
  
- hosts: tag_cpt_slave
  user: "{{ user }}"
  sudo: yes
  gather_facts: true
  tasks:
   - name: setup hostname
     hostname: name="{{ ec2_tag_Name }}"
   - debug: msg="{{ ec2_tag_Name }}"
   
