- name: check marathon container
  command: docker ps -a
  register: containers

- name: run marathon
  shell: docker run --net="host" --name=pintostack-marathon-container -d pintostack/pintostack-marathon --master zk://{{ansible_default_ipv4.address}}:2181/mesos --zk zk://{{ansible_default_ipv4.address}}:2181/marathon
  when: "{{ 'pintostack-marathon-container' not in containers.stdout }}"