# This ansible playbook brings up the world according to host groups in inventory file

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  tasks:
   - name: Check hosts UP and SSH is listening before taking actions
     local_action: wait_for
        host="{{ansible_ssh_host}}"
        port="{{ansible_ssh_port}}"
        state="started"
        delay=3
        connect_timeout=2
        timeout=300
   - name: INFO
     local_action: debug
        msg="If you fail on this step try execute  source source.global && ansible-playbook -i ${ANSIBLE_INVENTORY_FILE} provisioning/world-playbook.yml"

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  sudo: yes
  tasks:
   - name: Warming up docker cache with pintostack/pintostack-mesos-slave
     shell: docker pull pintostack/pintostack-mesos-slave 

- hosts: masters
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  gather_facts: true
  vars:
     masters_str: |
        {% set comma = joiner(",") %}
        {% set eth = "ansible_"+vpc_if %}
        {% for item in groups["masters"] -%}
            {{ comma() }}{{ hostvars[item][eth].ipv4.address }}
        {%- endfor %}
  pre_tasks:
    - set_fact:
        a_vpc_if: "ansible_{{ vpc_if }}"
    - set_fact:
        local_ip: "{{ hostvars[inventory_hostname][a_vpc_if].ipv4.address }}"
    - set_fact:
        masters : "{{ masters_str|trim|split(',') }}" 
    - set_fact:
        my_zoo_id : "{{ masters|index_of(local_ip) }}"
    - set_fact:
        my_zk_hostnames: "{{masters|join(':2181,')}}:2181"
    - set_fact:
        my_quorum: "{{ (masters|length)//2+1 }}"
    - set_fact:
        my_hostname: "master-{{ my_zoo_id }}"
    - debug:
        msg: "my_zk_hostnames {{ my_zk_hostnames }}"
    - debug:
        msg: "my_quorum {{ my_quorum }}"
    - debug:
        msg: "zoo_id={{ my_zoo_id }}"
  roles:

# TODO  zoo_id: "{{ my_zoo_id }}", zookeeper_hosts: "{{ masters|to_zk }}
    - role: pintostack-zk

# TODO: #      quorum: "{{ my_quorum }}",
    - role: pintostack-mesos-master

    - role: pintostack-marathon

- hosts: slaves
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  vars:
    public_dns : ["8.8.8.8", "8.8.4.4"]
    masters_str: |
        {% set comma = joiner(",") %}
        {% set eth = "ansible_"+vpc_if %}
        {% for item in groups["masters"] -%}
            {{ comma() }}{{ hostvars[item][eth].ipv4.address }}
        {%- endfor %}
  pre_tasks:
    - set_fact:
        masters : "{{ masters_str|trim|split(',') }}"
    - set_fact:
        my_zk_hostnames: "{{masters|join(':2181,')}}:2181"
    - set_fact:
        a_vpc_if: "ansible_{{ vpc_if }}"
    - set_fact:
        local_ip: "{{ hostvars[inventory_hostname][a_vpc_if].ipv4.address }}"
  roles:
    - role: pintostack-mesos-slave
    - role: ansible-registrator
      registrator_consul_host: "{{ inventory_hostname }}.node.consul"
      registrator_consul_port: "8500"
      registrator_log_file: "/var/log/registrator.log"
