# This ansible playbook brings up the world according to host groups in inventory file
- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  tasks:
   - name: Check hosts UP and SSH is listening before taking actions
     local_action: wait_for
        host="{{ansible_ssh_host}}"
        port="{{ansible_ssh_port}}"
        state="started"
        delay=3
        connect_timeout=2
        timeout=300
   - name: INFO
     local_action: debug
        msg="If you fail on this step try again or your host is down."

- hosts: master-1
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  gather_facts: false
  roles:
    - role: ansible-squid3

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  gather_facts: true
  pre_tasks:
    - set_fact:
        a_vpc_if: "ansible_{{ vpc_if }}"
    - set_fact:
        local_ip: "{{ hostvars[inventory_hostname][a_vpc_if].ipv4.address }}"
    - set_fact:
        proxy_ip: "{{ hostvars['master-1'][a_vpc_if].ipv4.address }}"

  tasks:
   - name: iptables installed
     apt: pkg=iptables state=present
     when: inventory_hostname != 'master-1'

   - name: ufw installed
     apt: pkg=ufw state=present
     when: inventory_hostname != 'master-1'

   - name: start UFW
     shell: start ufw
     when: inventory_hostname != 'master-1'

   - name: add NAT to proxy
     shell: iptables -t nat -I OUTPUT -p tcp --dport 80 -j DNAT --to-destination {{ proxy_ip }}:3127
     when: inventory_hostname != 'master-1'
