# This ansible playbook brings up the world according to host groups in inventory file

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  tasks:
   - name: Check hosts UP and SSH is listening before taking actions
     local_action: wait_for
        host="{{ansible_ssh_host}}"
        port="{{ansible_ssh_port}}"
        state="started"
        delay=3
        connect_timeout=2
        timeout=300
   - name: INFO
     local_action: debug
        msg="If you fail on this step try again or your host is down."

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  gather_facts: false
  tasks:
   - name: ensure group vagrant exists
     group: name=vagrant state=present

   - name: ensure user in group vagrant
     user: name={{ansible_ssh_user}} append=yes groups=vagrant

   - name: add group vagrant NO PASSWORD sudo
     lineinfile: dest=/etc/sudoers state=present regexp='^%vagrant ALL\=' line='%vagrant ALL=(ALL{{":"}} ALL) NOPASSWD{{":"}} ALL' validate='visudo -cf %s'
